base_commit: b6e5b1a8ba32b63e5277961f8e577ce8451c3d21
created_at: '2021-04-20T02:39:47Z'
datasets:
- SWE-bench/SWE-bench_Multimodal
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.highlightjs_1776_highlight.js-3154:latest
image_assets:
  patch: []
  problem_statement:
  - https://user-images.githubusercontent.com/297533/115327884-ba074080-a15d-11eb-82c3-05ed21739f23.png
  test_patch: []
instance_id: highlightjs__highlight.js-3154
log_parser: parse_log_highlightjs
repo: highlightjs/highlight.js
split: test
version: '11.0'
