base_commit: ca64b1b3535b97b440441c5b50a114e8a30f76af
created_at: '2019-06-19T07:25:43Z'
datasets:
- SWE-bench/SWE-bench_Multimodal
eval_type: fail_only
image: swebench/sweb.eval.x86_64.bpmn-io_1776_bpmn-js-1092:latest
image_assets:
  patch: []
  problem_statement:
  - https://user-images.githubusercontent.com/58601/59662199-bf378500-91ac-11e9-82dc-a2e20af3acce.gif
  - https://user-images.githubusercontent.com/58601/59662218-c78fc000-91ac-11e9-96df-a9aa58acbed1.gif
  test_patch: []
instance_id: bpmn-io__bpmn-js-1092
log_parser: parse_log_bpmn_js
repo: bpmn-io/bpmn-js
split: test
version: '4.0'
