base_commit: 196d3afbf44de116c84936ff20cf4a5b8056ccb7
created_at: '2022-01-15T02:12:40Z'
datasets:
- SWE-bench/SWE-bench_Multimodal
eval_type: fail_only
image: swebench/sweb.eval.x86_64.processing_1776_p5.js-5555:latest
image_assets:
  patch: []
  problem_statement:
  - https://user-images.githubusercontent.com/3698659/149576927-bed39ec9-30ff-4afa-9db8-d2984a167ed1.png
  - https://user-images.githubusercontent.com/3698659/149577198-0d6a2acb-ba23-4f64-b3d1-70c416f153fc.png
  test_patch: []
instance_id: processing__p5.js-5555
log_parser: parse_log_p5js
repo: processing/p5.js
split: dev
version: '1.4'
