base_commit: c6ddb3e1897f7c2ab14102143a9474364ef7c1d8
created_at: '2024-04-30T23:25:39Z'
datasets:
- SWE-bench/SWE-bench_Multimodal
eval_type: fail_only
image: swebench/sweb.eval.x86_64.openlayers_1776_openlayers-15787:latest
image_assets:
  patch: []
  problem_statement: []
  test_patch:
  - path: test/rendering/cases/cog-palette-add-remove/expected.png
    url: https://raw.githubusercontent.com/openlayers/openlayers/431914b46e9d63cf0e5bba6e0e89c45b596a76f6/test/rendering/cases/cog-palette-add-remove/expected.png
instance_id: openlayers__openlayers-15787
log_parser: parse_log_openlayers
repo: openlayers/openlayers
split: test
version: '9.1'
