base_commit: 84bf801b5267201c1ca5b33d390c34e8f0db6d3b
created_at: '2019-03-14T10:52:16Z'
datasets:
- SWE-bench/SWE-bench_Multimodal
eval_type: fail_only
image: swebench/sweb.eval.x86_64.openlayers_1776_openlayers-9333:latest
image_assets:
  patch:
  - path: rendering/data/tiles/512x256/5/3/12.png
    url: https://raw.githubusercontent.com/openlayers/openlayers/7510a19c739c644f15f76333114b64d431b10555/rendering/data/tiles/512x256/5/3/12.png
  - path: rendering/data/tiles/osm/0/0/0.png
    url: https://raw.githubusercontent.com/openlayers/openlayers/7510a19c739c644f15f76333114b64d431b10555/rendering/data/tiles/osm/0/0/0.png
  - path: rendering/data/tiles/osm/5/4/12.png
    url: https://raw.githubusercontent.com/openlayers/openlayers/7510a19c739c644f15f76333114b64d431b10555/rendering/data/tiles/osm/5/4/12.png
  - path: rendering/data/tiles/osm/5/5/12.png
    url: https://raw.githubusercontent.com/openlayers/openlayers/7510a19c739c644f15f76333114b64d431b10555/rendering/data/tiles/osm/5/5/12.png
  - path: rendering/data/tiles/osm/5/5/13.png
    url: https://raw.githubusercontent.com/openlayers/openlayers/7510a19c739c644f15f76333114b64d431b10555/rendering/data/tiles/osm/5/5/13.png
  - path: rendering/data/tiles/osm/5/6/12.png
    url: https://raw.githubusercontent.com/openlayers/openlayers/7510a19c739c644f15f76333114b64d431b10555/rendering/data/tiles/osm/5/6/12.png
  - path: rendering/data/tiles/osm/5/6/13.png
    url: https://raw.githubusercontent.com/openlayers/openlayers/7510a19c739c644f15f76333114b64d431b10555/rendering/data/tiles/osm/5/6/13.png
  - path: rendering/data/tiles/wms/wms0.png
    url: https://raw.githubusercontent.com/openlayers/openlayers/7510a19c739c644f15f76333114b64d431b10555/rendering/data/tiles/wms/wms0.png
  - path: rendering/data/tiles/wms/wms20.png
    url: https://raw.githubusercontent.com/openlayers/openlayers/7510a19c739c644f15f76333114b64d431b10555/rendering/data/tiles/wms/wms20.png
  problem_statement: []
  test_patch:
  - path: rendering/cases/layer-image/expected.png
    url: https://raw.githubusercontent.com/openlayers/openlayers/7510a19c739c644f15f76333114b64d431b10555/rendering/cases/layer-image/expected.png
  - path: rendering/cases/layer-tile-none-square/expected.png
    url: https://raw.githubusercontent.com/openlayers/openlayers/7510a19c739c644f15f76333114b64d431b10555/rendering/cases/layer-tile-none-square/expected.png
  - path: rendering/cases/layer-tile-opacity/expected.png
    url: https://raw.githubusercontent.com/openlayers/openlayers/7510a19c739c644f15f76333114b64d431b10555/rendering/cases/layer-tile-opacity/expected.png
  - path: rendering/cases/layer-tile-two-layers/expected.png
    url: https://raw.githubusercontent.com/openlayers/openlayers/7510a19c739c644f15f76333114b64d431b10555/rendering/cases/layer-tile-two-layers/expected.png
  - path: rendering/cases/layer-vector-decluttering/expected.png
    url: https://raw.githubusercontent.com/openlayers/openlayers/7510a19c739c644f15f76333114b64d431b10555/rendering/cases/layer-vector-decluttering/expected.png
  - path: rendering/cases/layer-vector-polygon-partial/expected.png
    url: https://raw.githubusercontent.com/openlayers/openlayers/7510a19c739c644f15f76333114b64d431b10555/rendering/cases/layer-vector-polygon-partial/expected.png
  - path: rendering/cases/layer-vector-polygon/expected.png
    url: https://raw.githubusercontent.com/openlayers/openlayers/7510a19c739c644f15f76333114b64d431b10555/rendering/cases/layer-vector-polygon/expected.png
  - path: rendering/cases/layer-vector/expected.png
    url: https://raw.githubusercontent.com/openlayers/openlayers/7510a19c739c644f15f76333114b64d431b10555/rendering/cases/layer-vector/expected.png
  - path: rendering/cases/layer-vectorimage/expected.png
    url: https://raw.githubusercontent.com/openlayers/openlayers/7510a19c739c644f15f76333114b64d431b10555/rendering/cases/layer-vectorimage/expected.png
  - path: rendering/cases/layer-vectortile-rotate-hidpi/expected.png
    url: https://raw.githubusercontent.com/openlayers/openlayers/7510a19c739c644f15f76333114b64d431b10555/rendering/cases/layer-vectortile-rotate-hidpi/expected.png
  - path: rendering/cases/map-pan/expected.png
    url: https://raw.githubusercontent.com/openlayers/openlayers/7510a19c739c644f15f76333114b64d431b10555/rendering/cases/map-pan/expected.png
  - path: rendering/cases/map/expected.png
    url: https://raw.githubusercontent.com/openlayers/openlayers/7510a19c739c644f15f76333114b64d431b10555/rendering/cases/map/expected.png
  - path: rendering/cases/multipoint-style/expected.png
    url: https://raw.githubusercontent.com/openlayers/openlayers/7510a19c739c644f15f76333114b64d431b10555/rendering/cases/multipoint-style/expected.png
  - path: rendering/cases/point-style/expected.png
    url: https://raw.githubusercontent.com/openlayers/openlayers/7510a19c739c644f15f76333114b64d431b10555/rendering/cases/point-style/expected.png
  - path: rendering/cases/regularshape-style/expected.png
    url: https://raw.githubusercontent.com/openlayers/openlayers/7510a19c739c644f15f76333114b64d431b10555/rendering/cases/regularshape-style/expected.png
  - path: rendering/cases/source-raster/expected.png
    url: https://raw.githubusercontent.com/openlayers/openlayers/7510a19c739c644f15f76333114b64d431b10555/rendering/cases/source-raster/expected.png
  - path: rendering/cases/source-tilewms-gutter0/expected.png
    url: https://raw.githubusercontent.com/openlayers/openlayers/7510a19c739c644f15f76333114b64d431b10555/rendering/cases/source-tilewms-gutter0/expected.png
  - path: rendering/cases/source-tilewms-gutter20/expected.png
    url: https://raw.githubusercontent.com/openlayers/openlayers/7510a19c739c644f15f76333114b64d431b10555/rendering/cases/source-tilewms-gutter20/expected.png
  - path: rendering/cases/text-style-linestring-nice/expected.png
    url: https://raw.githubusercontent.com/openlayers/openlayers/7510a19c739c644f15f76333114b64d431b10555/rendering/cases/text-style-linestring-nice/expected.png
  - path: rendering/cases/text-style-linestring-ugly/expected.png
    url: https://raw.githubusercontent.com/openlayers/openlayers/7510a19c739c644f15f76333114b64d431b10555/rendering/cases/text-style-linestring-ugly/expected.png
  - path: rendering/cases/text-style-overlap/expected.png
    url: https://raw.githubusercontent.com/openlayers/openlayers/7510a19c739c644f15f76333114b64d431b10555/rendering/cases/text-style-overlap/expected.png
instance_id: openlayers__openlayers-9333
log_parser: parse_log_openlayers
repo: openlayers/openlayers
split: deprecated
version: '5.3'
