base_commit: 12c5f9a8396f2a472f331ef772d6c7ba5cd62513
created_at: '2021-10-13T17:29:13Z'
datasets:
- SWE-bench/SWE-bench_Multimodal
eval_type: fail_only
image: swebench/sweb.eval.x86_64.chartjs_1776_chart.js-9766:latest
image_assets:
  patch: []
  problem_statement: []
  test_patch:
  - path: test/fixtures/controller.line/stacking/bounds-data.png
    url: https://raw.githubusercontent.com/chartjs/Chart.js/871293fb6caf7b7a63dd6249e9fc39b99a121c2d/test/fixtures/controller.line/stacking/bounds-data.png
instance_id: chartjs__Chart.js-9766
log_parser: parse_log_chart_js
repo: chartjs/Chart.js
split: dev
version: '3.5'
