base_commit: c961db4bf2ba81581c7c0eda02e9fc5f5ef78f01
created_at: '2021-05-31T10:23:16Z'
datasets:
- SWE-bench/SWE-bench_Multimodal
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.diegomura_1776_react-pdf-1341:latest
image_assets:
  patch: []
  problem_statement:
  - https://user-images.githubusercontent.com/3676669/119581286-7ec0e880-bd7f-11eb-8eb6-0983bf4c8f45.png
  test_patch: []
instance_id: diegomura__react-pdf-1341
log_parser: parse_log_react_pdf
repo: diegomura/react-pdf
split: dev
version: '2.0'
