base_commit: e0ee93f138b7da294a28db50b97c22977fdfc8ed
created_at: '2021-04-17T20:16:51Z'
datasets:
- SWE-bench/SWE-bench_Multimodal
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.prismjs_1776_prism-2861:latest
image_assets:
  patch: []
  problem_statement:
  - https://user-images.githubusercontent.com/50064165/115120019-c49acc00-9fdd-11eb-81b3-aa0260fcec2d.png
  test_patch: []
instance_id: PrismJS__prism-2861
log_parser: parse_log_prismjs
repo: PrismJS/prism
split: test
version: '1.23'
