base_commit: aaf8a69067010e1bb61428a409c7d8850872721d
created_at: '2023-01-25T05:21:55Z'
datasets:
- SWE-bench/SWE-bench_Multimodal
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.grommet_1776_grommet-6600:latest
image_assets:
  patch: []
  problem_statement:
  - https://user-images.githubusercontent.com/23144209/214194624-4aa9d356-8147-4e54-b80b-adcfaca2d046.png
  - https://user-images.githubusercontent.com/23144209/214194768-12e83091-d46f-4cbc-83b7-b0f326d0e390.png
  test_patch: []
instance_id: grommet__grommet-6600
log_parser: parse_log_grommet
repo: grommet/grommet
split: test
version: '2.29'
