base_commit: 5ea0b52ba8774e8170dc18fb6453affdef43eafc
created_at: '2020-02-18T13:21:08Z'
datasets:
- SWE-bench/SWE-bench_Multimodal
eval_type: fail_only
image: swebench/sweb.eval.x86_64.openlayers_1776_openlayers-10694:latest
image_assets:
  patch: []
  problem_statement: []
  test_patch:
  - path: rendering/cases/icon-opacity/expected.png
    url: https://raw.githubusercontent.com/openlayers/openlayers/341e482f309bd55bf37a13c959046bf058d0f8ce/rendering/cases/icon-opacity/expected.png
instance_id: openlayers__openlayers-10694
log_parser: parse_log_openlayers
repo: openlayers/openlayers
split: test
version: '6.2'
