base_commit: 24d762a0fe3a92500f92323b038a2389cb6ecae5
created_at: '2018-04-05T00:45:55Z'
datasets:
- SWE-bench/SWE-bench_Multimodal
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.automattic_1776_wp-calypso-23915:latest
image_assets:
  patch: []
  problem_statement:
  - https://user-images.githubusercontent.com/51896/37911883-0e6ddc30-30c6-11e8-8bb5-a28724d7945e.png
  test_patch: []
instance_id: Automattic__wp-calypso-23915
log_parser: parse_log_calypso
repo: Automattic/wp-calypso
split: dev
version: 8.11.0
