base_commit: c80b1450f55189a03bf3781e04559eb9b68f2129
created_at: '2022-02-13T17:09:19Z'
datasets:
- SWE-bench/SWE-bench_Multimodal
eval_type: fail_only
image: swebench/sweb.eval.x86_64.chartjs_1776_chart.js-10157:latest
image_assets:
  patch: []
  problem_statement:
  - https://user-images.githubusercontent.com/10648471/146602938-9d5be17b-e050-4a9a-b9ac-5f9f51e08e8b.png
  test_patch:
  - path: test/fixtures/controller.bar/minBarLength/horizontal-neg.png
    url: https://raw.githubusercontent.com/chartjs/Chart.js/368ad3cf70414de7769852cf52693c08aaf9e05c/test/fixtures/controller.bar/minBarLength/horizontal-neg.png
  - path: test/fixtures/controller.bar/minBarLength/horizontal-pos.png
    url: https://raw.githubusercontent.com/chartjs/Chart.js/368ad3cf70414de7769852cf52693c08aaf9e05c/test/fixtures/controller.bar/minBarLength/horizontal-pos.png
  - path: test/fixtures/controller.bar/minBarLength/horizontal-stacked.png
    url: https://raw.githubusercontent.com/chartjs/Chart.js/368ad3cf70414de7769852cf52693c08aaf9e05c/test/fixtures/controller.bar/minBarLength/horizontal-stacked.png
  - path: test/fixtures/controller.bar/minBarLength/vertical-neg.png
    url: https://raw.githubusercontent.com/chartjs/Chart.js/368ad3cf70414de7769852cf52693c08aaf9e05c/test/fixtures/controller.bar/minBarLength/vertical-neg.png
  - path: test/fixtures/controller.bar/minBarLength/vertical-pos.png
    url: https://raw.githubusercontent.com/chartjs/Chart.js/368ad3cf70414de7769852cf52693c08aaf9e05c/test/fixtures/controller.bar/minBarLength/vertical-pos.png
  - path: test/fixtures/controller.bar/minBarLength/vertical-stacked.png
    url: https://raw.githubusercontent.com/chartjs/Chart.js/368ad3cf70414de7769852cf52693c08aaf9e05c/test/fixtures/controller.bar/minBarLength/vertical-stacked.png
instance_id: chartjs__Chart.js-10157
log_parser: parse_log_chart_js
repo: chartjs/Chart.js
split: dev
version: '3.7'
