base_commit: 4117dadf3858a64fb23d0020d3f468afa1d7fc87
created_at: '2020-03-27T05:12:03Z'
datasets:
- SWE-bench/SWE-bench_Multimodal
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.alibaba-fusion_1776_next-1720:latest
image_assets:
  patch: []
  problem_statement:
  - https://fusion-image.oss-cn-beijing.aliyuncs.com/images/3rE4GYcPGCtd.png
  - https://fusion-image.oss-cn-beijing.aliyuncs.com/images/nqK89bNdkup1.png
  test_patch: []
instance_id: alibaba-fusion__next-1720
log_parser: parse_log_next
repo: alibaba-fusion/next
split: test
version: '1.19'
