base_commit: d98b923a7c71c6e8f224024fda145e90802910a0
created_at: '2022-10-18T20:35:27Z'
datasets:
- SWE-bench/SWE-bench_Multimodal
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.carbon-design-system_1776_carbon-12332:latest
image_assets:
  patch: []
  problem_statement:
  - https://user-images.githubusercontent.com/15144993/178540731-44f32bdf-6a55-47b8-a670-37bfac00251b.png
  test_patch: []
instance_id: carbon-design-system__carbon-12332
log_parser: parse_log_carbon
repo: carbon-design-system/carbon
split: test
version: '16.18'
