base_commit: b751de512b3026fe7c5d35596afb362b1287a3f6
created_at: '2019-07-08T20:54:42Z'
datasets:
- SWE-bench/SWE-bench_Multimodal
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.googlechrome_1776_lighthouse-9334:latest
image_assets:
  patch: []
  problem_statement:
  - https://user-images.githubusercontent.com/4071474/57647804-ca2d4300-7578-11e9-9a46-de594e51bbe6.png
  test_patch: []
instance_id: GoogleChrome__lighthouse-9334
log_parser: parse_log_lighthouse
repo: GoogleChrome/lighthouse
split: test
version: '5.1'
