base_commit: bfcbc302cb3598c79ce9564993972eeb531bd2ff
created_at: '2017-06-20T21:04:47Z'
datasets:
- SWE-bench/SWE-bench_Multimodal
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.googlechrome_1776_lighthouse-2553:latest
image_assets:
  patch: []
  problem_statement:
  - https://cloud.githubusercontent.com/assets/39191/22953538/77aa4268-f2c6-11e6-8c09-bdde89f12de1.png
  test_patch: []
instance_id: GoogleChrome__lighthouse-2553
log_parser: parse_log_lighthouse
repo: GoogleChrome/lighthouse
split: test
version: '2.1'
