base_commit: cdc0894012916c7adf2202fb515679f97cddd41c
created_at: '2022-02-21T10:18:11Z'
datasets:
- SWE-bench/SWE-bench_Multimodal
eval_type: fail_only
image: swebench/sweb.eval.x86_64.bpmn-io_1776_bpmn-js-1607:latest
image_assets:
  patch: []
  problem_statement:
  - https://user-images.githubusercontent.com/58601/154928284-a2c61a19-dd32-44d0-82b0-ac4c9b9534a0.png
  - https://user-images.githubusercontent.com/58601/154928464-2b3838de-133c-4a9c-9f6f-73226211a050.png
  test_patch: []
instance_id: bpmn-io__bpmn-js-1607
log_parser: parse_log_bpmn_js
repo: bpmn-io/bpmn-js
split: test
version: '9.0'
