base_commit: 8c4526d5f1b5f151d6a0acebb2310d10ed76e16b
created_at: '2023-04-14T20:57:27Z'
datasets:
- SWE-bench/SWE-bench_Multimodal
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.scratchfoundation_1776_scratch-gui-8891:latest
image_assets:
  patch: []
  problem_statement:
  - https://user-images.githubusercontent.com/106490990/196005751-2c5dfdd1-8538-42ce-a5d6-222c73703a76.png
  - https://user-images.githubusercontent.com/106490990/196005804-8eb0d6ea-98fc-4fd0-a4c7-b46a6f42d1f7.png
  test_patch: []
instance_id: scratchfoundation__scratch-gui-8891
log_parser: parse_log_carbon
repo: scratchfoundation/scratch-gui
split: test
version: '8'
