base_commit: 47c2bc5d96d87f121a0ada42ddf60090f98a6339
created_at: '2021-08-23T17:07:00Z'
datasets:
- SWE-bench/SWE-bench_Multimodal
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.googlechrome_1776_lighthouse-12970:latest
image_assets:
  patch: []
  problem_statement:
  - https://user-images.githubusercontent.com/1780212/129445134-3bb7aa81-4507-4110-a505-8fcaa2ad36d4.png
  test_patch: []
instance_id: GoogleChrome__lighthouse-12970
log_parser: parse_log_lighthouse
repo: GoogleChrome/lighthouse
split: test
version: '8.3'
