base_commit: 8d68b119bcb95af182cc69d42acad8490af53d3e
created_at: '2021-09-02T16:42:37Z'
datasets:
- SWE-bench/SWE-bench_Multimodal
eval_type: fail_only
image: swebench/sweb.eval.x86_64.chartjs_1776_chart.js-9613:latest
image_assets:
  patch: []
  problem_statement:
  - https://user-images.githubusercontent.com/21239979/130746913-786e3664-9bd2-4562-904c-03d09089020f.png
  test_patch: []
instance_id: chartjs__Chart.js-9613
log_parser: parse_log_chart_js
repo: chartjs/Chart.js
split: dev
version: '3.5'
