base_commit: 706955dfd99294e1edfe9b95652dd8492674f20a
created_at: '2021-08-30T20:01:24Z'
datasets:
- SWE-bench/SWE-bench_Multimodal
eval_type: fail_only
image: swebench/sweb.eval.x86_64.openlayers_1776_openlayers-12683:latest
image_assets:
  patch: []
  problem_statement:
  - https://user-images.githubusercontent.com/88471/131383210-f7507bb7-fa16-49f1-a4a6-2f6ac518f351.png
  - https://user-images.githubusercontent.com/88471/131382965-8143c6dc-71a6-4cae-9ebf-6ff6139b35ab.png
  - https://user-images.githubusercontent.com/88471/131383037-0df9d621-1687-4867-959d-f0a7c6d8e8e7.png
  test_patch:
  - path: test/rendering/cases/icon-sprite/expected.png
    url: https://raw.githubusercontent.com/openlayers/openlayers/df493725c6489c1112ec8ad48287f42c1f265bec/test/rendering/cases/icon-sprite/expected.png
  - path: test/rendering/data/sprites/gis_symbols.png
    url: https://raw.githubusercontent.com/openlayers/openlayers/df493725c6489c1112ec8ad48287f42c1f265bec/test/rendering/data/sprites/gis_symbols.png
instance_id: openlayers__openlayers-12683
log_parser: parse_log_openlayers
repo: openlayers/openlayers
split: test
version: '6.6'
