base_commit: 892a70e0d3011349155d2f82d56a99532f23fd19
created_at: '2020-12-10T11:35:59Z'
datasets:
- SWE-bench/SWE-bench_Multimodal
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.prettier_1776_prettier-9866:latest
image_assets:
  patch: []
  problem_statement:
  - https://user-images.githubusercontent.com/23690145/69402850-06b1d680-0d34-11ea-891b-4a39dc14012a.gif
  test_patch: []
instance_id: prettier__prettier-9866
log_parser: parse_log_carbon
repo: prettier/prettier
split: test
version: '2.3'
