base_commit: c9fb107b94ffa5f2b905509a0407588b85476b02
created_at: '2022-08-28T13:07:54Z'
datasets:
- SWE-bench/SWE-bench_Multimodal
eval_type: fail_only
image: swebench/sweb.eval.x86_64.processing_1776_p5.js-5771:latest
image_assets:
  patch: []
  problem_statement:
  - https://user-images.githubusercontent.com/5315059/187053713-e8562d29-3958-4b5a-8c3a-c7b3fd091910.png
  - https://user-images.githubusercontent.com/5315059/187053706-c374deb2-22ae-4e81-b27c-d3ee66dd3452.png
  test_patch: []
instance_id: processing__p5.js-5771
log_parser: parse_log_p5js
repo: processing/p5.js
split: dev
version: '1.4'
