base_commit: 52151068bdc7e95150a189392fbd5ec0a48318f0
created_at: '2018-07-07T18:59:40Z'
datasets:
- SWE-bench/SWE-bench_Multimodal
eval_type: fail_only
image: swebench/sweb.eval.x86_64.processing_1776_p5.js-3068:latest
image_assets:
  patch: []
  problem_statement:
  - https://user-images.githubusercontent.com/1088194/42413671-bb74b886-81d9-11e8-8434-f8c0a14ef113.png
  test_patch: []
instance_id: processing__p5.js-3068
log_parser: parse_log_p5js
repo: processing/p5.js
split: dev
version: '0.6'
