base_commit: 4b87e771f2e388c607dd96a474f5837e772f9826
created_at: '2019-07-18T10:40:16Z'
datasets:
- SWE-bench/SWE-bench_Multimodal
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.alibaba-fusion_1776_next-895:latest
image_assets:
  patch: []
  problem_statement:
  - https://fusion-image.oss-cn-beijing.aliyuncs.com/images/o4qRe8STzJu7.png
  test_patch: []
instance_id: alibaba-fusion__next-895
log_parser: parse_log_next
repo: alibaba-fusion/next
split: test
version: '1.16'
