base_commit: da071c9e408faceec944c0df4b8d4fac43c47d3d
created_at: '2020-11-15T16:49:45Z'
datasets:
- SWE-bench/SWE-bench_Multimodal
eval_type: fail_only
image: swebench/sweb.eval.x86_64.markedjs_1776_marked-1825:latest
image_assets:
  patch: []
  problem_statement:
  - https://user-images.githubusercontent.com/613788/99151858-00ff8000-266c-11eb-942f-f9596eb92482.png
  - https://user-images.githubusercontent.com/613788/99151912-618ebd00-266c-11eb-9c5c-331921f3c2ef.png
  - https://user-images.githubusercontent.com/613788/99151858-00ff8000-266c-11eb-942f-f9596eb92482.png
  - https://user-images.githubusercontent.com/613788/99151912-618ebd00-266c-11eb-9c5c-331921f3c2ef.png
  test_patch: []
instance_id: markedjs__marked-1825
log_parser: parse_log_marked
repo: markedjs/marked
split: dev
version: '1.2'
