base_commit: a715b1f5c6a64f80298fd424306f2bafb9752e4c
created_at: '2021-11-16T17:23:53Z'
datasets:
- SWE-bench/SWE-bench_Multimodal
eval_type: fail_only
image: swebench/sweb.eval.x86_64.openlayers_1776_openlayers-13013:latest
image_assets:
  patch: []
  problem_statement:
  - https://user-images.githubusercontent.com/6855297/141603391-ded521d5-04e8-4a7c-9f11-27ae60dc5b90.png
  test_patch:
  - path: test/rendering/cases/webgl-data-tile-3-band/expected.png
    url: https://raw.githubusercontent.com/openlayers/openlayers/611d45570874dd7cc3361db6f6dd4d183e74f325/test/rendering/cases/webgl-data-tile-3-band/expected.png
  - path: test/rendering/cases/webgl-data-tile-loosely-packed/expected.png
    url: https://raw.githubusercontent.com/openlayers/openlayers/611d45570874dd7cc3361db6f6dd4d183e74f325/test/rendering/cases/webgl-data-tile-loosely-packed/expected.png
instance_id: openlayers__openlayers-13013
log_parser: parse_log_openlayers
repo: openlayers/openlayers
split: test
version: '6.9'
