base_commit: eb1aca6e4a7cf826b7ffa1e24a1075846747e344
created_at: '2023-04-24T15:48:41Z'
datasets:
- SWE-bench/SWE-bench_Multimodal
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.quarto-dev_1776_quarto-cli-5292:latest
image_assets:
  patch: []
  problem_statement:
  - https://user-images.githubusercontent.com/41155337/234010331-0d354cc5-fd81-47b2-8b9c-8b2bd20981d3.png
  test_patch: []
instance_id: quarto-dev__quarto-cli-5292
log_parser: parse_log_quarto_cli
repo: quarto-dev/quarto-cli
split: deprecated
version: ''
