base_commit: b26f56bd316a3ed11c33f50cd4a3dac44a4ee529
created_at: '2024-06-04T07:41:01Z'
datasets:
- SWE-bench/SWE-bench_Multimodal
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.prettier_1776_prettier-16347:latest
image_assets:
  patch: []
  problem_statement:
  - https://waline.js.org/logo.png
  - https://file.mo7.cc/static/lxh_gif/lxh_71.gif
  - https://file.mo7.cc/disk/blog_preview_en.png
  - https://guoxicheng.top/logo.png
  - https://waline.js.org/logo.png
  - https://file.mo7.cc/static/lxh_gif/lxh_71.gif
  - https://file.mo7.cc/disk/blog_preview_en.png
  - https://guoxicheng.top/logo.png
  test_patch: []
instance_id: prettier__prettier-16347
log_parser: parse_log_carbon
repo: prettier/prettier
split: test
version: '3.4'
