base_commit: 9e445e13dd96de61e7b7c5c98ad98e12268a4d12
created_at: '2019-08-18T08:35:34Z'
datasets:
- SWE-bench/SWE-bench_Multimodal
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.automattic_1776_wp-calypso-35531:latest
image_assets:
  patch: []
  problem_statement:
  - https://user-images.githubusercontent.com/18581859/63221565-9afe2180-c1b8-11e9-9a21-75af5cd75175.png
  - https://user-images.githubusercontent.com/18581859/63221567-9b96b800-c1b8-11e9-927f-52d47ead4789.png
  test_patch: []
instance_id: Automattic__wp-calypso-35531
log_parser: parse_log_calypso
repo: Automattic/wp-calypso
split: dev
version: 10.15.2
