base_commit: d26b26215ff150ad29fec5ce1ed02bc02deaa691
created_at: '2020-02-18T14:36:53Z'
datasets:
- SWE-bench/SWE-bench_Multimodal
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.alibaba-fusion_1776_next-1586:latest
image_assets:
  patch: []
  problem_statement:
  - https://dailyfusion.oss-cn-hangzhou.aliyuncs.com/images/0Rx0VYBcNZQt.png
  - https://dailyfusion.oss-cn-hangzhou.aliyuncs.com/images/NcPseyNqAT8A.png
  - https://dailyfusion.oss-cn-hangzhou.aliyuncs.com/images/ZDthkOiO6q2K.png
  test_patch: []
instance_id: alibaba-fusion__next-1586
log_parser: parse_log_next
repo: alibaba-fusion/next
split: test
version: '1.19'
