base_commit: 167adb2904f5be7111e0ab1360c03db54f74c972
created_at: '2020-04-23T07:43:06Z'
datasets:
- SWE-bench/SWE-bench_Multimodal
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.alibaba-fusion_1776_next-1788:latest
image_assets:
  patch: []
  problem_statement:
  - https://dailyfusion.oss-cn-hangzhou.aliyuncs.com/images/zARbCrONJeZ4.png
  - https://dailyfusion.oss-cn-hangzhou.aliyuncs.com/images/EsF8LJYajp7g.png
  test_patch: []
instance_id: alibaba-fusion__next-1788
log_parser: parse_log_next
repo: alibaba-fusion/next
split: test
version: '1.19'
