base_commit: 0f70132be18769c36b33740c99276e355b0b8702
created_at: '2021-07-16T20:40:14Z'
datasets:
- SWE-bench/SWE-bench_Multimodal
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.highlightjs_1776_highlight.js-3278:latest
image_assets:
  patch: []
  problem_statement:
  - https://user-images.githubusercontent.com/2077433/125857694-b04f2efe-a0d2-41f7-a955-d99162837aa4.png
  - https://user-images.githubusercontent.com/2077433/125858275-4952da72-a336-48c6-85b5-19b46f1f04bc.png
  test_patch: []
instance_id: highlightjs__highlight.js-3278
log_parser: parse_log_highlightjs
repo: highlightjs/highlight.js
split: test
version: '11.2'
