base_commit: 210ea21e8c9b3db1cfe6cede8b1602f8c25a66f1
created_at: '2023-03-16T18:38:10Z'
datasets:
- SWE-bench/SWE-bench_Multimodal
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.carbon-design-system_1776_carbon-13364:latest
image_assets:
  patch: []
  problem_statement:
  - https://user-images.githubusercontent.com/56201575/205992241-28771f13-0e83-4b12-a36d-f02c648944cf.png
  - https://user-images.githubusercontent.com/56201575/205992553-b1d77f4d-489b-48a6-bad7-6681ade5a800.png
  test_patch: []
instance_id: carbon-design-system__carbon-13364
log_parser: parse_log_carbon
repo: carbon-design-system/carbon
split: test
version: '18.15'
