base_commit: 4bd856aab025d4081d650d45402c7fcab78ccb1e
created_at: '2022-11-06T19:13:35Z'
datasets:
- SWE-bench/SWE-bench_Multimodal
eval_type: fail_only
image: swebench/sweb.eval.x86_64.processing_1776_p5.js-5855:latest
image_assets:
  patch: []
  problem_statement:
  - https://user-images.githubusercontent.com/5315059/200186009-b63449c6-38e4-4b35-8b01-7f807cd6ec5a.png
  - https://user-images.githubusercontent.com/5315059/200186082-5789a1c4-fbc4-4dd3-a244-54c96f0ee608.png
  test_patch: []
instance_id: processing__p5.js-5855
log_parser: parse_log_p5js
repo: processing/p5.js
split: dev
version: '1.5'
