base_commit: 7baefd7bc33b2c0e2caf61322e7e950d10f737fe
created_at: '2022-01-24T14:29:46Z'
datasets:
- SWE-bench/SWE-bench_Multimodal
eval_type: fail_only
image: swebench/sweb.eval.x86_64.bpmn-io_1776_bpmn-js-1584:latest
image_assets:
  patch: []
  problem_statement:
  - https://user-images.githubusercontent.com/15230555/147228024-18c202f6-9b3f-4128-8469-1ce583273a3c.gif
  test_patch: []
instance_id: bpmn-io__bpmn-js-1584
log_parser: parse_log_bpmn_js
repo: bpmn-io/bpmn-js
split: test
version: '8.9'
