base_commit: 8dbbbb35d6fb90ce8ebdd2c884077a53e72597f0
created_at: '2021-03-07T14:02:52Z'
datasets:
- SWE-bench/SWE-bench_Multimodal
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.prismjs_1776_prism-2792:latest
image_assets:
  patch: []
  problem_statement:
  - https://user-images.githubusercontent.com/46059092/85927276-e8e5ba80-b89c-11ea-97d2-8403367e12d6.png
  test_patch: []
instance_id: PrismJS__prism-2792
log_parser: parse_log_prismjs
repo: PrismJS/prism
split: test
version: '1.23'
