base_commit: 810c37fcd0032af04e4926f9fab16d1f93b212cb
created_at: '2021-01-21T19:22:39Z'
datasets:
- SWE-bench/SWE-bench_Multimodal
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.highlightjs_1776_highlight.js-2969:latest
image_assets:
  patch: []
  problem_statement:
  - https://user-images.githubusercontent.com/2564094/103803917-25d9f900-5006-11eb-9f32-744eafdd2946.png
  - https://user-images.githubusercontent.com/2564094/103804513-19a26b80-5007-11eb-9a72-2e8b175f17f4.png
  - https://user-images.githubusercontent.com/2564094/103803726-d09de780-5005-11eb-895b-93988c9a95a4.png
  test_patch: []
instance_id: highlightjs__highlight.js-2969
log_parser: parse_log_highlightjs
repo: highlightjs/highlight.js
split: test
version: '10.5'
