base_commit: abcb4f5fed26beab75096f5db131354bfd033bb5
created_at: '2018-07-16T22:03:03Z'
datasets:
- SWE-bench/SWE-bench_Multimodal
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.grommet_1776_grommet-2124:latest
image_assets:
  patch: []
  problem_statement:
  - https://user-images.githubusercontent.com/13810084/42769349-ee82f324-88ef-11e8-83b0-ed03f65cb146.png
  test_patch: []
instance_id: grommet__grommet-2124
log_parser: parse_log_grommet
repo: grommet/grommet
split: test
version: '2.0'
