base_commit: 1caa09d3ced20d2a67e4e5b1ba5ca28ec441ea49
created_at: '2021-03-15T18:25:52Z'
datasets:
- SWE-bench/SWE-bench_Multimodal
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.carbon-design-system_1776_carbon-8092:latest
image_assets:
  patch: []
  problem_statement:
  - https://user-images.githubusercontent.com/43969356/110999669-5a3f9d80-8346-11eb-85d9-3c80a3e30036.png
  test_patch: []
instance_id: carbon-design-system__carbon-8092
log_parser: parse_log_carbon
repo: carbon-design-system/carbon
split: test
version: '14'
