base_commit: 69702de9f245b2b960fa24f127e5e3b2b3d21ecc
created_at: '2023-01-23T09:35:01Z'
datasets:
- SWE-bench/SWE-bench_Multimodal
eval_type: fail_only
image: swebench/sweb.eval.x86_64.processing_1776_p5.js-5970:latest
image_assets:
  patch: []
  problem_statement:
  - https://user-images.githubusercontent.com/39549290/213927281-3d1c54a5-7f16-464a-a205-a70074609e25.png
  test_patch: []
instance_id: processing__p5.js-5970
log_parser: parse_log_p5js
repo: processing/p5.js
split: dev
version: '1.5'
