base_commit: cace136694462665ce4aa9b8a8cd6373df940d31
created_at: '2020-02-28T16:56:43Z'
datasets:
- SWE-bench/SWE-bench_Multimodal
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.carbon-design-system_1776_carbon-5485:latest
image_assets:
  patch: []
  problem_statement:
  - https://user-images.githubusercontent.com/56437682/67013426-01d18580-f0eb-11e9-8f9e-88bb1208cebc.png
  test_patch: []
instance_id: carbon-design-system__carbon-5485
log_parser: parse_log_carbon
repo: carbon-design-system/carbon
split: test
version: '12'
